<?php

/** === GAME-IDs === */
const GID_ROULETTE = 1;
const GID_BLACKJACK = 2;
const GID_HITTHENICK = 3;
const GID_SLOTS = 4;
const GID_POKER = 5;

/** === ERRORS === */
const ERR_INVALID_JSON = 6001;
const ERR_CHECKIN_REQUIRED = 6002;
const ERR_CHECKIN_DATA_INVALID = 6003;
const ERR_API_TOKEN_INVALID = 6004;

const ERR_MISSING_BIDS = 6101;
const ERR_BIDS_OVER_BALANCE = 6102;
const ERR_MISSING_ACTION = 6103;
const ERR_INVALID_ACTION = 6104;
const ERR_MISSING_USER_INPUT = 6105;
const ERR_MISSING_DATA = 6106;
const ERR_LOBBY_JOIN_FAILED = 6107;

const ERR_SERVER_INTERNAL = 6500;
